---
title: "Figure 2"
author: "Shawn Williams"
date: "5/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(ggsci)
library(survival)
source('Helper Functions/Survival_Functions.R')


mypal = pal_jama()(7)


## color scheme 
col_scheme.expanded <- c('Zim53;765' = mypal[4],
                         'line_765-hybrid' = mypal[2],
                         'Zim53;315' = mypal[1],
                         'iPLA2-VIA[Delta174]' = mypal[3],
                         'Zim53;315 x\niPLA2-VIA[Delta174]' = mypal[5],
                         'iPLA2-VIA[Delta174] x\nZim53;765' = mypal[6] )

```

```{r Figure 2a}
stv <- read_excel('Figure 2/Raw Data/2017JUN Balancer Mapping Count Sheet.xlsx')  %>%
  filter(! is.na(Dead)) %>%
  separate(Condition, into = c('Genotype', 'Marker','Replicate'),sep = "_") 

#Set up survival data into format for model input 

Dead=stv$Dead # creates a variable with the number of deaths
survFormat<- data.frame() # initialize empty data 
#frame to store the expanded tables 

for (iter in 1:dim(stv)[1]){
  i=0
  while (i < Dead[iter]){
    i = i+1 
    TMP<- stv[iter,]
    TMP$deaths=1
    survFormat<- rbind(survFormat,TMP) }
}

chr.levels <- c('none','chr2','chr3','chr2,3')

survFormat %>%
  mutate(Replicate = factor(Replicate)) %>%
  mutate(Marker = fct_recode(Marker,'none' = 'wt')) %>%
  mutate(Marker = factor(Marker,levels = chr.levels)) %>%
  mutate(Genotype = fct_recode(Genotype, 
                               'line_765-hybrid' = 'siI;765')) -> survFormat
  
survFormat %>%
  filter(Genotype %in% c('Zim53;765','line_765-hybrid')) %>%
  mutate(Marker = factor(Marker,levels = chr.levels)) -> survFormat.765


x.y <- survfit(Surv(Age, deaths == 1)~ Genotype + Marker, data = survFormat.765)

survival_df(x.y) %>%
  separate(Condition, into = c('Genotype', 'Marker'),sep = ", ") %>%
  mutate(Genotype = factor(surv.delevel(Genotype),
                           levels = c('Zim53;765', 'line_765-hybrid'))) %>%
  mutate(Marker=factor(surv.delevel(Marker))) %>%
  mutate(Marker=str_remove_all(Marker, '\\s')) %>%
  mutate('chr' = factor(Marker, levels = chr.levels)) %>%
  
  ggplot(aes(x = time, y = survival, color = chr)) +
  geom_line(size = 1.8, linetype = 1) +
  xlab('Time (hrs)')+
  ylab('Survival')+
  xlim(c(0,175))+
  scale_colour_aaas(name = c('Heterozygous\nchromosome'))+
  facet_grid(~Genotype)+
  theme_bw(base_size = 11 )+
  theme(panel.grid = element_blank(),
        legend.position = 'right')
ggsave(filename = 'Figure 2/figure2a.pdf',device = 'pdf',width = 5,height = 4)

# table for appendix 
stv %>%
  filter(Genotype == 'Zim53;765') %>%
  dplyr::select(-Censor) %>%
  write_csv('Figure 2/StarvationCounts_figure2a.csv')

summary(x.y)$table %>%
  as_tibble(rownames = 'Condition') %>%
  separate(Condition, into = c('Genotype', 'Marker'),sep = ", ") %>%
  mutate(Genotype = factor(surv.delevel(Genotype))) %>%
  mutate(Marker=factor(surv.delevel(Marker))) %>%
  mutate(Marker=str_remove_all(Marker, '\\s')) %>%
  #mutate('chr' = factor(Marker, levels = chr.levels)) %>%
  dplyr::select(Genotype,Marker,`*rmean`:median) %>%
  `colnames<-`(c('Genotype','Marker','Mean','SEM','Median'))%>%
  write_csv('Figure 2/SummaryTable_figure2a.csv')

```


```{r Figure 2a stats}
# make sample variable with genotype and marker
survFormat.765 %>%
  filter(Genotype == 'Zim53;765') %>%
  mutate(sample = paste(Genotype, Marker, sep = '_')) -> survFormat.765

survFormat.765 %>%
  pull(sample) %>%
  unique() -> samples_geno



comb.pairs <- combn(samples_geno, 2)
p.vec <- c() # set empty variable to store pvalues for each pairwise comparison
for (i in 1:6){ # iterate through total # of combinations
  df.diff <- survdiff(Surv(Age, deaths == 1) ~ 
                 sample, 
                 data= filter(survFormat.765,
                              sample %in% comb.pairs[,i])) # get suv diff for each pair
  pval <- pchisq(df.diff$chisq, length(df.diff$n)-1, lower.tail = FALSE) # calc p val for the contrast
  p.vec <- c(p.vec,pval) # store pval 
}



as_tibble(t(comb.pairs)) %>%
            add_column('pval' = p.adjust(p.vec,method = 'bonferroni')) %>%
  `colnames<-`(c("Genotype 1", "Genotype 2", "pval")) %>%
  write_csv('Figure 2/statistics_figure2a.csv')

```


```{r Figure 2c}
mm <- read_excel('Figure 2/Raw Data/2019APR MeioticMapping Count Sheet.xlsx')

# Convert to survival format 
Surv.exp.mm <- mm %>%
  mutate_at(.vars = c('Cage','Genotype','Recombinant','ShortHand', 'Replicate'),.funs = factor) %>%
  gather(Time,Death, -c('Cage','Genotype','Recombinant','ShortHand', 'Replicate')) %>%
  mutate(Time=qf(Time))%>%
  mutate_at(.vars = 'Time',.funs = as.double) %>%
  filter(! is.na(Death)) 


Dead=Surv.exp.mm$Death # creates a variable with the number of deaths
Surv.exp.MM<- data.frame() # initialize empty data 
#frame to store the expanded tables 

for (iter in 1:dim(Surv.exp.mm)[1]){
  i=0
  while (i < Dead[iter]){
    i = i+1 
    TMP<- Surv.exp.mm[iter,]
    TMP$deaths=1
    Surv.exp.MM<- rbind(Surv.exp.MM,TMP) }
}



Surv.exp.MM %>%
  mutate(Recombinant = factor(Recombinant)) %>%
  filter(Recombinant %in% c('1','2','5')) -> Surv.exp.MM # only keep recombinant with enough sample size to be meaningfull 


x<- survfit(Surv(Time, deaths == 1) ~ 
              Genotype + Recombinant, data= Surv.exp.MM )

survival_df(x) %>%
  separate(Condition, into = c('Genotype', 'Recombinant'),sep = ", ") %>%
  mutate(Genotype=factor(surv.delevel(Genotype))) %>%
  mutate(Recombinant=factor(surv.delevel(Recombinant))) %>%
  mutate(Genotype = if_else(Genotype == 'Zim53;765', true = 'Zim53;765', false = 'line_765-hybrid')) %>%
  mutate( Recombinant = fct_recode(Recombinant, 'i' = '1',
                                   'ii' = '2', 'v' = '5'))-> sf.df
  

 
  sf.df %>%
  ggplot(aes(x = time, y = survival, color = Genotype)) +
  geom_line(size = 1.8) +
  xlab('Time (hrs)')+
  ylab('Survival')+
  scale_colour_manual(name = c('Parent'),values= col_scheme.expanded)+
    facet_grid(~ Recombinant)+

  theme_bw(base_size = 11 )+
  theme(panel.grid = element_blank(), legend.position = 'bottom')
ggsave(filename = 'Figure 2/figure2c.pdf',device = 'pdf',width = 7,height = 4)
```


```{r Figure 2c stats}
# make sample variable with genotype and recombinant
Surv.exp.MM %>%
  mutate(sample = paste(Genotype, Recombinant, sep = '_')) -> Surv.exp.MM

Surv.exp.MM %>%
  pull(sample) %>%
  unique() -> samples_geno



comb.pairs <- combn(samples_geno, 2)
p.vec <- c() # set empty variable to store pvalues for each pairwise comparison
for (i in 1:15){ # iterate through total # of combinations
  df.diff <- survdiff(Surv(Time, deaths == 1) ~ 
                 sample, 
                 data= filter(Surv.exp.MM,
                              sample %in% comb.pairs[,i])) # get suv diff for each pair
  pval <- pchisq(df.diff$chisq, length(df.diff$n)-1, lower.tail = FALSE) # calc p val for the contrast
  p.vec <- c(p.vec,pval) # store pval 
}



as_tibble(t(comb.pairs)) %>%
            add_column('pval' = p.adjust(p.vec,method = 'bonferroni')) %>%
  `colnames<-`(c("Genotype 1", "Genotype 2", "pval")) %>%
  as_tibble() %>%
  write_csv('Figure 2/statistics_figure2c.csv')

```


