---
title: "Figure 5"
author: "Shawn Williams"
date: "5/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(ggsci)
library(survival)
library(ggsci)
source('Helper Functions/Survival_Functions.R')
mypal = pal_jama()(7)
```

```{r Figure 5}
dm.1  <- read_excel('Figure 5/Raw Data/2020MAR iPLA2-VIA Complementation Count Sheet.xlsx', sheet = 2)
dm.2  <- read_excel('Figure 5/Raw Data/2020MAR iPLA2-VIA Complementation Count Sheet.xlsx',sheet = 3)


# Convert to survival format 
Surv.exp.CandidateValidations <- dm.1 %>%
  full_join(dm.2) %>%
  mutate_at(.vars = c('Cage','F_parent','M_Parent'),.funs = factor) %>%
  gather(Time,Death, -c('Cage','F_parent','M_Parent')) %>%
  mutate(Time=qf(Time))%>%
  mutate_at(.vars = 'Time',.funs = as.double) %>%
  filter(! is.na(Death)) 


Dead=Surv.exp.CandidateValidations$Death # creates a variable with the number of deaths
survFormat.CandidateValidations<- data.frame() # initialize empty data 
#frame to store the expanded tables 

for (iter in 1:dim(Surv.exp.CandidateValidations)[1]){
  i=0
  while (i < Dead[iter]){
    i = i+1 
    TMP<- Surv.exp.CandidateValidations[iter,]
    TMP$deaths=1
    survFormat.CandidateValidations<- rbind(survFormat.CandidateValidations,TMP) }
}


x.CandidateValidations<- survfit(Surv(Time, deaths == 1) ~ 
                 F_parent+M_Parent, data= survFormat.CandidateValidations)


summary(x.CandidateValidations)$table %>%
  as_tibble(rownames = 'Condition') %>%
  separate(Condition, into = c('F_Parent', 'M_Parent'),sep = ", ") %>%
  mutate(F_Parent = factor(surv.delevel(F_Parent))) %>%
  mutate(M_Parent=factor(surv.delevel(M_Parent))) %>%
  mutate(M_Parent=str_remove_all(M_Parent, '\\s')) %>%
  #mutate('chr' = factor(Marker, levels = chr.levels)) %>%
  dplyr::select(F_Parent,M_Parent,events:median) %>%
  `colnames<-`(c('F_Parent','F_Parent', 'Events', 'Mean','SEM','Median'))%>%
  write_csv('Figure 5/SummaryTable_figure5.csv')
```


```{r Figure 5}
# Convert to survival format 
Surv.exp.CandidateValidations <- dm.1 %>%
  full_join(dm.2) %>%
  mutate_at(.vars = c('Cage','F_parent','M_Parent'),.funs = factor) %>%
  gather(Time,Death, -c('Cage','F_parent','M_Parent')) %>%
  mutate(Time=qf(Time))%>%
  mutate_at(.vars = 'Time',.funs = as.double) %>%
  filter(! is.na(Death)) 
## Joining, by = c("Cage", "F_parent", "M_Parent", "t8", "t16", "t24", "t32", "t40", "t48", "t56", "t64", "t72", "t80", "t88", "t96", "t104", "t112", "t120")
Dead=Surv.exp.CandidateValidations$Death # creates a variable with the number of deaths
survFormat.CandidateValidations<- data.frame() # initialize empty data 
#frame to store the expanded tables 

for (iter in 1:dim(Surv.exp.CandidateValidations)[1]){
  i=0
  while (i < Dead[iter]){
    i = i+1 
    TMP<- Surv.exp.CandidateValidations[iter,]
    TMP$deaths=1
    survFormat.CandidateValidations<- rbind(survFormat.CandidateValidations,TMP) }
}


x.CandidateValidations<- survfit(Surv(Time, deaths == 1) ~ 
                 F_parent+M_Parent, data= survFormat.CandidateValidations)


survival_df(x.CandidateValidations) %>%
  separate(Condition, into = c('Female_Parent', 'Male_Parent'),sep = ", ") %>%
   mutate(Female_Parent=factor(surv.delevel(Female_Parent))) %>%
   mutate(Male_Parent=factor(surv.delevel(Male_Parent))) %>%
   filter(!(Male_Parent == "Zim53;315" & Female_Parent == "Zim53;315")) %>%
  
   mutate(Female_Parent = fct_recode(Female_Parent ,
                                     'iPLA2-VIA[Delta174]' = '80133',
                                     'iPLA2-VIA[Delta192]' = '80134')) %>%
  mutate(Male_Parent = str_remove_all(Male_Parent, '\\s')) %>%
  

  mutate(Male_Parent = as.character(Male_Parent)) %>%
            mutate(Male_Parent = fct_recode(Male_Parent ,
                                     'iPLA2-VIA[Delta174]' = '80133',
                                     'iPLA2-VIA[Delta192]' = '80134')) %>%

  
  ggplot(aes(x = time, y = survival, color = Female_Parent)) +
  geom_line(size = 1.2) +
  scale_color_manual(name = "Female Parent", values = c('Zim53;765' = mypal[4],
                                                        'Zim53;315' = mypal[1],
                                                        'iPLA2-VIA[Delta174]' = mypal[3],
                                                        'iPLA2-VIA[Delta192]' = 'grey50',
                                                        'DGRP-765' = 'grey80' ))+ 
  xlab('Time (hrs)')+
  ylab('Survival')+
  facet_wrap(~ Male_Parent) +
  theme_bw(base_size = 11 )+
  theme(panel.grid = element_blank())
ggsave(filename = 'Figure 5/figure5.pdf',device = 'pdf',width = 7,height = 7)







```

```{r Figure 5 stats }
# make cross variable with female_male geno
survFormat.CandidateValidations %>%
  mutate(cross = paste(F_parent, M_Parent, sep = '_')) -> survFormat.CandidateValidations

survFormat.CandidateValidations %>%
  pull(cross) %>%
  unique() -> crosses 



comb.pairs <- combn(crosses, 2)
p.vec <- c() # set empty variable to store pvalues for each pairwise comparison
for (i in 1:66){ # iterate through total # of combinations
  df.diff <- survdiff(Surv(Time, deaths == 1) ~ 
                 cross, 
                 data= filter(survFormat.CandidateValidations,
                              cross %in% comb.pairs[,i])) # get suv diff for each pair
  pval <- pchisq(df.diff$chisq, length(df.diff$n)-1, lower.tail = FALSE) # calc p val for the contrast
  p.vec <- c(p.vec,pval) # store pval 
}



as_tibble(t(comb.pairs)) %>%
            add_column('pval' = p.adjust(p.vec,method = 'bonferroni')) %>%
  `colnames<-`(c("Genotype 1", "Genotype 2", "pval")) %>%
  write_csv('Figure 5/statistics_iPLA2VIA_complementation.csv')





```
